apps/home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
	path("", views.index, name = 'index'),

	path("add/<int:producto_id>/carrito/", views.add_carrito, name = 'add-carrito'),
	path("delete/<int:producto_id>/carrito/", views.delete_producto_carrito, name = 'delete-carrito'),
	path("vaciar/carrito/", views.limpiar_carrito, name = 'vaciar-carrito'),

	path('crear/pedido/', views.hacer_pedido, name = 'hacer-pedido'),

	path(
		'usuario/<int:usuario_id>/lista/pedidos/', 
		views.lista_pedidos_usuario, 
		name = 'pedido-lista'
	),
	path(
		'usuario/<int:usuario_id>/detalle/<int:pedido_id>/pedido/', 
		views.detalle_pedido_usuario, 
		name = 'pedido'
	),

]

apps/usuario/urls.py
from django.urls import path

from . import views

app_name = 'usuarios'
urlpatterns = [
	path('crear/', views.crear_usuario , name = 'crear-usuario'),
	path('login/', views.login_usuario , name = 'login'),
	path('logout/', views.logout_usuario , name = 'logout'),
	path('confirmar-logout/', views.confirmar_logout , name = 'confirmar-logout'),
	path('config/<int:pk>/usuario/', views.settings_usuario , name = 'config-usuario'),
	path('update/password/<int:pk>/usuario/', views.update_usuario_password , name = 'update-password'),
	path('update/email/<int:pk>/usuario/', views.update_usuario_email , name = 'update-email'),

]

carrito/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.home.urls')),
    path('usuario/', include('apps.usuario.urls'))

]

apps/usuario/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser

from . import managers
# Create your models here.


class Usuario(AbstractBaseUser):
	nombre = models.CharField(max_length = 50, blank=True, null=True)
	apellido = models.CharField(max_length = 50, blank=True, null=True)
	email = models.EmailField(unique=True)

	is_active = models.BooleanField(default = True )
	is_admin = models.BooleanField(default = False)
	is_staff = models.BooleanField(default = False)
	is_superadmin = models.BooleanField(default = False)


	objects = managers.UsuarioManager()

	USERNAME_FIELD = 'email'
	REQUIRED_FIELDS = ['nombre', 'apellido']

	class Meta:
		verbose_name = 'Usuario'
		verbose_name_plural = 'Usuarios'

	def has_perm(self, perm, obj = None):
		return self.is_admin

	def has_module_perms(self, add_label):
		return True

	def nombre_completo(self):
		return f"{self.nombre} {self.apellido}"

	def get_username(self):
		return f"{self.email[ :  self.email.find('@') + 1]}"


	def __str__(self):
		return f"{self.email}"

apps/usuario/forms.py
from django import forms
from django.contrib.auth import authenticate
from django.utils.translation import gettext_lazy as _

from . import models


class CrearUsuario(forms.ModelForm):
	password_1 = forms.CharField(label = 'Contraseña', required = True , widget = forms.PasswordInput(
			attrs = {
				"placeholder": "Contraseña",
				'class': 'form-control form-control-lg',
				'id': 'password-input'
			}
		))
	password_2 = forms.CharField(label = 'Confirmar Contraseña', required = True , widget = forms.PasswordInput(
			attrs = {
				"placeholder": "Repetir Contraseña",
				'class': 'form-control form-control-lg',
				'id': 'password-conf-input'
			}
		))

	class Meta:
		model = models.Usuario
		fields = (
			'nombre',
			'apellido',
			'email'
		)

		widgets={
			'nombre': forms.TextInput( 
				attrs = {
					'class': 'form-control form-control-lg', 
					'id': 'nombre-input'
				}
			),
			'apellido': forms.TextInput( 
				attrs = {
					'class': 'form-control form-control-lg', 
					'id': 'apellido-input'
				}
			),
			'email': forms.EmailInput( 
				attrs = {
					'class': 'form-control form-control-lg', 
					'id': 'apellido-input'
				}
			),
		}

	def clean_email(self):
		email = self.cleaned_data['email']

		if models.Usuario.objects.filter(email = email):
			self.add_error('email', 'Ya existe un usuario con este email.')

		return email

	def clean(self):
		self.cleaned_data = super().clean()

		password_1 = self.cleaned_data['password_1']
		password_2 = self.cleaned_data['password_2']

		if password_1 != password_2:
			raise forms.ValidationError('Las contraseñas no coinciden.')

		return self.cleaned_data

	def save(self):
		return models.Usuario.objects.create_user(
			email = self.cleaned_data['email'],
			password = self.cleaned_data['password_1'],
			nombre = self.cleaned_data['nombre'],
			apellido = self.cleaned_data['apellido'],
		)


class LoginForm(forms.Form):
	email = forms.EmailField(label = 'Email', required = True ,widget = forms.EmailInput(
		attrs = {"class": "form-control form-control-lg", 'id': 'email-input'}
	))
	password = forms.CharField(label = 'Contraseña', required = True , widget = forms.PasswordInput(
		attrs = {
			"placeholder": "Ingrese su contraseña",
			"class": "form-control form-control-lg", 
			'id': 'password-input'
		}
	))

	def clean(self):
		self.cleaned_data = super().clean()

		if not authenticate(email = self.cleaned_data['email'], password = self.cleaned_data['password']):
			raise forms.ValidationError('Las credenciales son invalidas')

		return self.cleaned_data


class UpdateUsuarioPassword(forms.Form):
	new_password = forms.CharField(label = 'Nueva Contraseña', required = True , widget = forms.PasswordInput(
			attrs = {
				"placeholder": "Contraseña",
				"class": "form-control form-control-lg",
				'id': 'new-password-input'
			}
		))


	email = forms.EmailField(label = 'Email', required = True, help_text = 'Introduce tus credenciales para confirmar la configuración',widget = forms.EmailInput(
		attrs = {
			"class": "form-control form-control-lg", 
			'id': 'email-input'
		}
	))
	password = forms.CharField(label = 'Contraseña', required = True , widget = forms.PasswordInput(
			attrs = {
				"placeholder": "Contraseña",
				"class": "form-control form-control-lg",
				"id": 'password-input'
			}
		))
	


	def clean_new_password(self):
		new_password = self.cleaned_data.get('new_password')

		if len(new_password) <= 4:
			self.add_error('new_password', 'La contraseña es muy corta.')

		return new_password

	def clean(self):
		self.cleaned_data = super().clean()

		if not authenticate(email = self.cleaned_data['email'], password = self.cleaned_data['password']):
			raise forms.ValidationError('Las credenciales son invalidas.')

		return self.cleaned_data

	


class UpdateUsuarioEmail(forms.Form):
	
	new_email = forms.EmailField(label = 'Nuevo Email', required = True,widget = forms.EmailInput(
		attrs = {
			"class": "form-control form-control-lg",
			"id": "new-email-input"
		}
	))
	
	email = forms.EmailField(label = 'Email', required = True, help_text = 'Introduce tus credenciales para confirmar la configuración', widget = forms.EmailInput(
		attrs = {
			"class": "form-control form-control-lg",
			"id": "email-input"
		}
	))
	password = forms.CharField(label = 'Confirmar Contraseña', required = True , widget = forms.PasswordInput(
		attrs = {
			"placeholder": "Contraseña",
			"class": "form-control form-control-lg",
			"id": "password-input"
		}
	))

	def clean_new_email(self):
		email = self.cleaned_data['new_email']

		if models.Usuario.objects.filter(email = email):
			self.add_error('email', 'Ya existe un usuario con este email.')

		return email

	def clean(self):
		self.cleaned_data = super().clean()

		if not authenticate(email = self.cleaned_data['email'], password = self.cleaned_data['password']):
			raise forms.ValidationError('Las credenciales son invalidas.')

		return self.cleaned_data

apps/usuario/views.py
from django.urls import reverse
from django.urls import reverse_lazy
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect
from django.http import Http404
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth import logout
from django.contrib.auth import authenticate
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods


from apps.home.carrito import Carrito
from . import forms
from . import models



# Create your views here.
@require_http_methods(['GET', 'POST'])
def crear_usuario(request):
	form = forms.CrearUsuario()

	if request.method == 'POST':
		form = forms.CrearUsuario(request.POST)

		if form.is_valid():
			usuario = form.save()

			messages.success(request, 'El usuario fue creado con existo.')

			return HttpResponseRedirect( reverse ('usuarios:login') )


	context = {'form': form}
	return render(request, 'usuario/crear_usuario.html', context)


@require_http_methods(['GET', 'POST'])
def login_usuario(request):
	if request.user.is_authenticated:
		return HttpResponseRedirect( reverse('home:index') )
	
	form = forms.LoginForm()

	if request.method == 'POST':
		form = forms.LoginForm(request.POST)

		if form.is_valid():
			
			usuario = authenticate(
				email = form.cleaned_data.get('email'), 
				password = form.cleaned_data.get('password')
			)

			login(request, usuario)

			messages.success(request, f'Bienvenido, {usuario.nombre} al sistema.')


			return HttpResponseRedirect( reverse ('home:index') )


	context = {
		'form': form
	}
	return render(request, 'usuario/login.html', context)

@require_http_methods(['GET'])
@login_required(login_url = reverse_lazy('usuarios:login'))
def logout_usuario(request):
	carrito = Carrito(request)

	if carrito.get_productos(request.user.id):
		return HttpResponseRedirect(reverse('usuarios:confirmar-logout'))

	logout(request)
	messages.success(request, 'Hasta pronto...')
	return HttpResponseRedirect(reverse('usuarios:login'))

@require_http_methods(['GET', 'POST'])
@login_required(login_url = reverse_lazy('usuarios:login'))
def confirmar_logout(request):
	carrito = Carrito(request)

	if request.method == 'POST':
		carrito.clean(request.user.id)
		return HttpResponseRedirect(reverse('usuarios:logout'))
	
	context = {}
	return render(request, 'usuario/confirmar_logout.html', context)


@require_http_methods(['GET'])
@login_required(login_url = reverse_lazy('usuarios:login'))
def settings_usuario(request, pk = None):
	try:
		usuario = get_object_or_404(models.Usuario, pk = pk)
	except Usuario.DoesNotExist:
		raise Http404('No existe un usuario con estos datos.')
	

	context = {
		'form_update_password': forms.UpdateUsuarioPassword(),
		'form_update_email': forms.UpdateUsuarioEmail(),
		'username': usuario.get_username()
	}
	return render(request, 'usuario/settings.html', context)


@require_http_methods(['GET', 'POST'])
@login_required(login_url = reverse_lazy('usuarios:login'))
def update_usuario_password(request, pk = None):
	form = forms.UpdateUsuarioPassword()

	try:
		usuario = get_object_or_404(models.Usuario, pk = pk)
	except Usuario.DoesNotExist:
		raise Http404('No existe un usuario con estos datos.')

	if request.method == 'POST':
		
		form = forms.UpdateUsuarioPassword(request.POST)

		if form.is_valid():
			usuario.set_password(form.cleaned_data.get('new_password'))
			usuario.save()

			messages.success(request, f'Su contraseña fue actualizada correctamente.')

			return HttpResponseRedirect(
				reverse('usuarios:config-usuario', kwargs = {'pk': usuario.id})
			)


	context = {
		'form': form,
		'username': usuario.get_username()
	}

	return render(request, 'usuario/update_password.html', context)


@require_http_methods(['GET', 'POST'])
@login_required(login_url = reverse_lazy('usuarios:login'))
def update_usuario_email(request, pk = None):
	form = forms.UpdateUsuarioEmail()

	try:
		usuario = get_object_or_404(models.Usuario, pk = pk)
	except Usuario.DoesNotExist:
		raise Http404('No existe un usuario con estos datos.')

	if request.method == "POST":
		form = forms.UpdateUsuarioEmail(request.POST)

		if form.is_valid():
			usuario.email = form.cleaned_data.get('new_email')
			usuario.save(update_fields=['email'])

			messages.success(request, f'Su email fue actualizado correctamente. {usuario.email}')

			return HttpResponseRedirect(
				reverse('usuarios:config-usuario', kwargs = {'pk': usuario.id})
			)

	context = {
		'form': form,
		'username': usuario.get_username()
	}

	return render(request, 'usuario/update_email.html', context)

templates/usuario/confirmar_logout.html
{% extends "base/base.html" %}


{% block title %} ¿Salir? {% endblock title %}

{% block content %}

<div class="container my-5">
  <div class="p-5 text-center bg-body-tertiary rounded-3">
    <h1 class="text-body-emphasis">¿Estas seguro que deseas salir?</h1>
    <p class="lead">
      Tienes productos en tu carrito de compras. Si sales, perderas esta información.
    </p>



    <div class="row text-center justify-content-center mt-4">
    	<div class="col-sm-4">
    		<form method="POST" action="{% url 'usuarios:confirmar-logout' %}"> {% csrf_token %}
				<button type="submit" class="w-100 btn btn-danger btn-lg">Sí, deseo salir.</button>
			</form>
    	</div>
    	<div class="col-sm-4">
    		<a href="{% url 'home:index' %}" class="w-100 btn btn-primary btn-lg"> No, quiero continuar.</a>
    	</div>

    	
		
    </div>
  </div>
</div>
	
{% endblock content %}

templates/usuario/crear_usuario.html
{% extends "base/base.html" %}

{% block title %} Crear Usuario{% endblock title %}

{% block content %}
	<div class="container mb-4">
		<h1 class="display-5 text-center my-4">Crear usuario</h1>

		<form method="POST" class="col-sm-5 col-lg-6 mx-auto"> {% csrf_token %}
			{% if form.errors %}
				{% if form.non_field_errors%}
					<div class="alert alert-danger alert-dismissible fade show" role="alert">

				      	{% for error in form.non_field_errors %}
				      		{{error}}
				      	{% endfor %}
						
						<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
					</div>
				{% endif %}
	      		
			{% endif %}
			
			{% for campo in form %}
				<div class="row g-3">
	      			<div class="col-12">
	      				{{campo.label_tag}}
	    				<div class="mb-2"></div>

	      				{{campo}}

	      				{% if campo.errors %}
	      					{% for error in campo.errors %}
	      						<div class="text-center">
	      							<span class="badge bg-danger-subtle border border-danger-subtle text-danger-emphasis rounded-pill">{{error}}</span>
	      						</div>
	      						
	      					{% endfor %}
	
						{% endif %}
	      			</div>
		    	</div>
	    		
	    		<div class="my-3"></div>

			
			{% endfor %}

	         <hr class="my-4">
			
			<button type="submit" class="w-100 btn btn-primary btn-lg">Crear</button>
		</form>
	</div>
	
{% endblock content %}

templates/usuario/login.html
{% extends "base/base.html" %}

{% block title %} Entrar {% endblock title %}

{% block content %}

	<div class="container mb-4">
		<h1 class="display-5 text-center my-4">Ingresar</h1>

		<form method="POST" class="col-sm-5 col-lg-6 mx-auto"> {% csrf_token %}
			{% if form.errors %}
				{% if form.non_field_errors%}
					<div class="alert alert-danger alert-dismissible fade show" role="alert">

				      	{% for error in form.non_field_errors %}
				      		{{error}}
				      	{% endfor %}
						
						<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
					</div>
				{% endif %}
		      		
			{% endif %}

			<div class="row g-3">
	      <div class="col-12">
	      	<label for="email-input" class="form-label">Email</label>
	       
					{{form.email}}
		
					 {% if form.email.errors %}
						 {% for error in  form.email.errors %}
								<div class="text-center">
		  							<span class="badge bg-danger-subtle border border-danger-subtle text-danger-emphasis rounded-pill">{{error}}</span>
		  						</div>
							{% endfor %}
					 {% endif %}
	      </div>
	    </div>
	        
	    <div class="my-3"></div>
	        
	    <div class="row g-3">
	        <div class="col-12">
	        	<label for="email-input" class="form-label">
		 					Contraseña
						</label>
						{{form.password}}

					 	{% if form.password.errors %}
					  
					  	{% for error in  form.password.errors %}
								<div class="text-center">
		  							<span class="badge bg-danger-subtle border border-danger-subtle text-danger-emphasis rounded-pill">{{error}}</span>
		  						</div>
							{% endfor %}
					 	{% endif %}
	        </div>
	    </div>

	     <hr class="my-4">
			
			<button type="submit" class="w-100 btn btn-primary btn-lg">Entrar</button>
		</form>
		
	</div>


{% endblock content %}

templates/usuario/settings.html
{% extends "base/base.html" %}

{% block title %} {{ username }} {% endblock title %}

{% block content %}
	<div class="pricing-header p-3 pb-md-4 mx-auto text-center">
		<h1 class="display-5 fw-normal text-body-emphasis"> Configuraciones del usuario - {{ username }}</h1>
	</div>

	<div class="mb-5"></div>
	
	<div class="container container-sm">
		<div class="row row-cols-1 row-cols-md-2 mb-3 text-center">
	      <div class="col">
	        <div class="card mb-4 rounded-3 shadow-sm">
	          <div class="card-header py-3">
	            <h4 class="my-0 fw-normal">Actualizar contraseña</h4>
	          </div>
	          <div class="card-body">
	            <p class="card-text">
	            	Configurar una nueva contraseña para tu usuario.
	            </p>
	            <a href="{% url 'usuarios:update-password' pk=request.user.id %}" class="w-100 btn btn-lg btn-outline-primary">Nueva Contraseña</a>
	          </div>
	        </div>
	      </div>
	      <div class="col">
	        <div class="card mb-4 rounded-3 shadow-sm">
	          <div class="card-header py-3">
	            <h4 class="my-0 fw-normal">Actualizar email</h4>
	          </div>
	          <div class="card-body">
	            <p class="card-text">
	            	Configurar un nuevo email para tu usuario.
	            </p>
	            <a href="{% url 'usuarios:update-email' pk=request.user.id %}" class="w-100 btn btn-lg btn-outline-primary">Nuevo Email</a>
	          </div>
	        </div>
	      </div>
	    </div>
	</div>


{% endblock content %}

templates/usuario/update_email.html
{% extends "base/base.html" %}

{% block title %} Nuevo Email {% endblock title %}

{% block content %}
	<div class="container">
		<div class="pricing-header p-3 pb-md-4 mx-auto text-center">
			<h1 class="display-5 text-center mt-4">Actualizar Email</h1>
			<p class="fs-5 text-body-secondary">
				(Actual: {{ request.user.email}})
			</p>
		</div>
		
		<form method="POST" class="col-sm-5 col-lg-6 mx-auto"> {% csrf_token %}
			{% if form.errors %}
				{% if form.non_field_errors%}
					<div class="alert alert-danger alert-dismissible fade show" role="alert">

				      	{% for error in form.non_field_errors %}
				      		{{error}}
				      	{% endfor %}
						
						<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
					</div>
				{% endif %}
	      		
			{% endif %}

			<div class="row g-3">
      			<div class="col-12">
      				<label for="new-email-input" class="form-label">Nuevo email</label>
      			</div>

      			{{form.new_email}}

      			{% if form.new_email.errors %}
					{% for error in  form.new_email.errors %}
						<div class="text-center">
  							<span class="badge bg-danger-subtle border border-danger-subtle text-danger-emphasis rounded-pill">{{error}}</span>
  						</div>
					{% endfor %}
				
				{% endif %}
    		</div>

     		<hr class="mb-5">

     		<h5 class="mb-3">
				<em>{{ form.email.help_text }}</em>
			</h5>

			<div class="row g-3">
	      		<div class="col-12">
	        		<label for="email-input" class="form-label">Email</label>

					{{ form.email }}

	      		</div>
	    	</div>

	    	<div class="row g-3">
	      		<div class="col-12">
	        		<label for="password-input" class="form-label">Password</label>

					{{ form.password }}

	      		</div>
	    	</div>
			
			<hr class="my-4">
		
			<button type="submit" class="w-100 btn btn-primary btn-lg">Guardar Cambios</button>
		</form>
	</div>
	

	
{% endblock content %}

templates/usuario/update_password.html
{% extends "base/base.html" %}

{% block title %} Nueva Contraseña {% endblock title %}


{% block content %}
	
	<div class="container">
		<h1 class="display-5 text-center mt-4 mb-5">Actualizar Contraseña</h1>

		<form method="POST" class="col-sm-5 col-lg-6 mx-auto"> {% csrf_token %}
			{% if form.errors %}
				{% if form.non_field_errors%}
					<div class="alert alert-danger alert-dismissible fade show" role="alert">

				      	{% for error in form.non_field_errors %}
				      		{{error}}
				      	{% endfor %}
						
						<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
					</div>
				{% endif %}
	      		
			{% endif %}

		<div class="row g-3">
      		<div class="col-12">
        		<label for="new-password-input" class="form-label">Nueva contraseña</label>

        		{{form.new_password}}

        		{% if form.new_password.errors %}
	        		{% for error in  form.new_password.errors %}
						<div class="text-center">
  							<span class="badge bg-danger-subtle border border-danger-subtle text-danger-emphasis rounded-pill">{{error}}</span>
  						</div>
					{% endfor %}
				  
				  	

				 {% endif %}
      		</div>
    	</div>

		
     	<hr class="mb-5">

		<h5 class="mb-3">
			<em>{{ form.email.help_text }}</em>
		</h5>

		<div class="row g-3">
      		<div class="col-12">
        		<label for="email-input" class="form-label">Email</label>

				{{ form.email }}

      		</div>
    	</div>

    	<div class="row g-3">
      		<div class="col-12">
        		<label for="password-input" class="form-label">Password</label>

				{{ form.password }}

      		</div>
    	</div>

     	<hr class="my-4">
		
		<button type="submit" class="w-100 btn btn-primary btn-lg">Guardar Cambios</button>
	</form>
	</div>
	
{% endblock content %}