apps/home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
	path("", views.index, name = 'index'),

	path("add/<int:producto_id>/carrito/", views.add_carrito, name = 'add-carrito'),
	path("delete/<int:producto_id>/carrito/", views.delete_producto_carrito, name = 'delete-carrito'),
	path("vaciar/carrito/", views.limpiar_carrito, name = 'vaciar-carrito'),

	path('crear/pedido/', views.hacer_pedido, name = 'hacer-pedido'),

	path(
		'usuario/<int:usuario_id>/lista/pedidos/', 
		views.lista_pedidos_usuario, 
		name = 'pedido-lista'
	),
	path(
		'usuario/<int:usuario_id>/detalle/<int:pedido_id>/pedido/', 
		views.detalle_pedido_usuario, 
		name = 'pedido'
	),

]

carrito/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.home.urls')),
    path('usuario/', include('apps.usuario.urls'))

]

apps/home/models.py
from django.db import models
from django.urls import reverse

from apps.usuario.models import Usuario

# Create your models here.
class Producto(models.Model):
	nombre = models.CharField(max_length = 30)
	precio = models.FloatField(default = 2.10)
	descripcion = models.TextField(max_length= 150)
	imagen = models.CharField(max_length = 30, blank=True, null=True)


	class Meta:
		verbose_name = 'Producto'
		verbose_name_plural = 'Productos'
		ordering = ['nombre']


	def __str__(self):
		return f"{self.nombre}"

class Pedido(models.Model):
	usuario = models.ForeignKey(
		Usuario,
		on_delete = models.SET_NULL,
		blank=True,
		null=True,
		related_name='pedidos'
	)
	total = models.FloatField(default = 0.0)
	creado = models.DateTimeField(auto_now_add=True)
	activo = models.BooleanField(default = True)


	class Meta:
		verbose_name = 'Pedido'
		verbose_name_plural = 'Pedidos'
		ordering = ['-creado']

	def get_absolute_url(self):
		return reverse('home:pedido', kwargs = {'pedido_id': self.pk, 'usuario_id': self.usuario.id})

	def __str__(self):
		return f"{self.creado}"


class DetallePedido(models.Model):
	pedido = models.ForeignKey(
		Pedido,
		related_name='detalle_pedido',
		on_delete = models.CASCADE,
		null = True,
		blank=True
	)
	productos = models.ForeignKey(
		Producto,
		related_name='detalle_pedido_productos',
		on_delete = models.CASCADE,
		null = True,
		blank=True
	)
	cantidad = models.PositiveSmallIntegerField(default = 1)


	class Meta:
		verbose_name = 'DetallePedido'
		verbose_name_plural = 'DetallePedidos'

	def __str__(self):
		return f"Nª: {self.id} - Pedido: {self.pedido}"

apps/home/views.py
from django.urls import reverse
from django.urls import reverse_lazy

from django.shortcuts import get_object_or_404
from django.shortcuts import render

from django.http import HttpResponseRedirect

from django.core.paginator import Paginator

from django.contrib import messages
from django.contrib.auth.decorators import login_required

from django.db.models import Prefetch

from django.views.decorators.http import require_http_methods

from apps.usuario.models import Usuario
from . import models
from .carrito import Carrito

# Create your views here.

@require_http_methods(['GET'])
def index(request):
	carrito = Carrito(request)

	productos = models.Producto.objects.all()
	productos_carrito = carrito.get_productos(request.user.id)

	context = {
		'productos': productos,
		'carrito': productos_carrito.values(),
		'total': carrito.get_gasto_total(request.user.id)
	}
	return render(request, 'home/index.html', context)

@require_http_methods(['POST'])
@login_required(login_url = reverse_lazy('usuarios:login'))
def add_carrito(request, producto_id=None):
	carrito = Carrito(request)

	try:
		producto = get_object_or_404(models.Producto, pk = producto_id)
	except models.Producto.DoesNotExist:
		raise e

	carrito.add(usuario = request.user.id, producto = producto)

	return HttpResponseRedirect(
		reverse('home:index')
	)


@require_http_methods(['POST'])
@login_required(login_url = reverse_lazy('usuarios:login'))
def delete_producto_carrito(request, producto_id=None):
	carrito = Carrito(request)

	carrito.delete(usuario = request.user.id, producto_id = producto_id)

	return HttpResponseRedirect(
		reverse('home:index')
	)
	

@require_http_methods(['POST'])
@login_required(login_url = reverse_lazy('usuarios:login'))
def limpiar_carrito(request):
	carrito = Carrito(request)

	carrito.clean(request.user.id)

	return HttpResponseRedirect(
		reverse('home:index')
	)


@require_http_methods(['GET'])
@login_required(login_url = reverse_lazy('usuarios:login'))
def lista_pedidos_usuario(request, usuario_id = None):

	pedidos = models.Pedido.objects.filter(
			usuario_id = usuario_id
		)

	paginator = Paginator(pedidos, 3)
	lista_pedidos = paginator.get_page(request.GET.get('page'))

	context = {
		'pedidos': lista_pedidos
	}

	return render(request, 'home/lista_pedidos.html', context)

@require_http_methods(['GET'])
@login_required(login_url = reverse_lazy('usuarios:login'))
def detalle_pedido_usuario(request, usuario_id = None,pedido_id = None):
	
	pedido = models.Pedido.objects.get(id = pedido_id, usuario_id = usuario_id)


	detalle_pedido = models.DetallePedido.objects.prefetch_related(
		Prefetch('productos')
	).filter(pedido_id = pedido.id)

	context = {
		'pedido': pedido,
		'detalle_pedido': detalle_pedido
	}

	return render(request, 'home/detalle_pedido.html', context)


@require_http_methods(['POST'])
@login_required(login_url = reverse_lazy('usuarios:login'))
def hacer_pedido(request):
	carrito = Carrito(request)

	productos = carrito.get_lista_productos()
	monto_total = carrito.get_gasto_total(request.user.id)


	if productos:
		pedido = models.Pedido(
			usuario = Usuario.objects.get(pk = request.user.id),
			total = monto_total
		)

		pedido.save()

		lista_productos = models.Producto.objects.filter(id__in = productos).order_by('id')
		productos_en_carrito = carrito.get_productos(request.user.id)
		

		lista_detalle_pedidos = []


		for pk, producto in zip(sorted(productos_en_carrito.keys()), lista_productos):
			cantidad = productos_en_carrito[pk]['total']

			detalle_pedido = models.DetallePedido(
				pedido = pedido,
				productos= producto,
				cantidad = cantidad
			)

			lista_detalle_pedidos.append(detalle_pedido)

		models.DetallePedido.objects.bulk_create(lista_detalle_pedidos)


		messages.success(request, 'El pedido fue realizado con exito.')

		carrito.clean(request.user.id)

		return HttpResponseRedirect(
			reverse(
				'home:pedido', 
				kwargs = {
					'pedido_id': pedido.id, 
					'usuario_id': request.user.id
				}
			)
			#reverse('home:pedido-lista')
		)
	
	messages.info(request, 'Usted no posee productos cargados en su carrito de compras.')

	return HttpResponseRedirect(
		reverse('home:index')
	)

templates/home/detalle_pedido.html
{% extends "base/base.html" %}

{% load humanize %}

{% block title %} Pedido {% endblock title %}

{% block content %}

	<div class="pricing-header p-3 pb-md-4 mx-auto text-center">
		<h1 class="display-4 fw-normal text-body-emphasis">Detalle del Pedido</h1>
		<p class="fs-5 text-body-secondary">
			Pedido creado:  {{pedido.creado|date:"D d N Y P"}}  <br>
			<small> {{pedido.creado|naturaltime}}</small>
		</p>
	</div>

	<div class="container container-sm">
		<div class="row row-cols-1 row-cols-2 row-cols-md-3 mb-3 text-center">
			{% for dtpedido in detalle_pedido %}
				<div class="col">
			        <div class="card mb-4 rounded-3 shadow-sm border-primary">
			          <div class="card-header py-3">
			            <h4 class="my-0 fw-normal">Producto Comprado</h4>
			          </div>
			          <div class="card-body">
			            <h1 class="card-title pricing-card-title">{{signo}}{{dtpedido.productos.precio}}</h1>
			            <p>
			            	
			            </p>
			            <ul class="list-unstyled mt-3 mb-4">
			              <li>Producto: <span class="badge rounded-pill text-bg-info">{{dtpedido.productos}}</span></li>
			             
			              <li>
			              	Cantidad comprada: <span class="badge bg-success-subtle border border-success-subtle text-success-emphasis rounded-pill">{{dtpedido.cantidad}}</span>
			              </li>
			            </ul>
			          </div>
			        </div>
		      	</div>
			{% endfor %}
	    </div>
	</div>
	<div class="container my-5">
	  	<div class="p-5 bg-body-tertiary rounded-3 text-center">
			<h3 class="display-6 fw-normal text-body-emphasis">Para un total de: {{pedido.total}}{{signo}}</h3>
		</div>
	</div>

	
	


{% endblock content %}

templates/home/index.html
{% extends "base/base.html" %}

{% load static %}

{% block title %} Inicio {% endblock title %}

{% block content %}
<div class="row g-5 m-2">
    <div class="col-md-8">
      	<h1 class="pb-4 mb-4 display-4 text-center text-body-emphasis fst-italic border-bottom">Catalago de productos</h1>

      	<div>
			{% if productos %}
				<div class="mt-5"></div>
				<div class="row  row-cols-1 row-cols-md-2 g-4" id="watch">
					{% for producto in productos %}
					 
						<div class="col">
				          	<div class="card">
				          	{% if producto.imagen %}
				          	 		<img src="{% static producto.imagen %}" class="card-img-top" width="100%" height="180">
				          	 		{% else %}
				          	 		<img src="{% static 'img/images.jpeg' %}" class="card-img-top" width="100%" height="180">
				          	 	{% endif %} 	
				          	
					            <div class="card-body">
					            	<h5 class="card-title">{{producto.nombre|title}}</h5>
					            	<p class="card-text">{{producto.descripcion|truncatechars:50}}</p>
					            	<small class="text-body-secondary">{{producto.precio|floatformat:2}} {{signo}}</small>
					            	
					            	<form method="POST" action="{% url 'home:add-carrito' producto_id=producto.id %}" class="text-center"> {% csrf_token %}
													
										<hr class="mt-2">

										{% if request.user.is_authenticated %}
											<button type="submit" class="btn btn-primary" id="add-car">Agregar al carrito</button>
											{% else %}

												<small class="text-body-secondary"> Para agregar al carrito debes ingresar al sistema.</small>
										{% endif %}
									</form>
					            </div>
				          	</div>
			        	</div>
		      		{% endfor %}
				</div>		
			{% endif %}
		</div>

    </div>

    <div class="col-md-4">
      <div class="position-sticky" style="top: 2rem;">
        {% if carrito %}
			<div class=" order-md-last">
			        <h4 class="d-flex justify-content-between align-items-center mb-3">
			        	<span class="text-primary">Mi carrito</span>
			          	<span class="badge bg-primary rounded-pill" id="total-productos">0</span>
			        </h4>
			        <ul class="list-group mb-3" id="list-productos">
			        	{% for producto in  carrito %}
			        		<li class="list-group-item d-flex justify-content-between lh-sm">
					            <div>
					            	<h6 class="my-0">{{ producto.nombre }}</h6>
						            <small class="text-body-secondary">Cantidad: {{ producto.total }}</small>

					             	<div class="my-2"></div>
					              	<div class="d-flex gap-2 justify-content-center">
					              		<form method="POST" action="{% url 'home:add-carrito' producto_id=producto.id %}"> {% csrf_token %}
												<button class="btn btn-sm-3 btn-outline-primary d-inline-fle-x align-items-center" type="submit">
											    +
											</button>
										</form>
										<form method="POST" action="{% url 'home:delete-carrito' producto_id=producto.id %}"> {% csrf_token %}
												<button class="btn btn-sm-3 btn-outline-danger d-inline-flex align-items-center" type="submit">
											    -
												</button>
										</form>			
									</div>
					            </div>
					            <span class="text-body-secondary">{{producto.precio}}{{signo}}</span>
					            
				          	</li>

			        	{% endfor %}
			        </ul>
			         <div class="d-flex gap-2 justify-content-center" id="event-car">
			         	<form class="card p-2" method="POST" action="{% url 'home:vaciar-carrito' %}"> {% csrf_token %}
				          <div class="input-group">
				            <button type="submit" class="btn btn-outline-warning">Vaciar Carrito</button>
				          </div>
				        </form>
				        <form class="card p-2" method="POST" action="{% url 'home:hacer-pedido' %}"> {% csrf_token %}
				          <div class="input-group">
				            <button type="submit" class="btn btn-outline-success">Realizar pedido</button>
				          </div>
				        </form>
			         </div>
		    </div>
			
	  
	   		{% else %}

			   <div class="order-md-last">
			        <h4 class="d-flex justify-content-between align-items-center mb-3">
			          <span class="text-primary">Mi carrito Vacio</span>
			          <span class="badge bg-primary rounded-pill">0</span>
			        </h4>
			        <ul class="list-group mb-3">
			        	<li class="list-group-item d-flex justify-content-between lh-sm">
			        		<h6 class="my-0">Sin productos</h6>
			        		<small class="text-body-secondary">0.0$</small>
			        	</li>
			        </ul>
			    </div>

		{% endif %}

      </div>
    </div>
  </div>
	

{% endblock content %}

	{% block script %}
		{% include "includes/total_productos_en_carrito.html" %}

	{% endblock script %}

templates/home/lista_pedidos.html
{% extends "base/base.html" %}

{% load humanize %}

{% load static %}

{% block title %} Pedidos {% endblock title %}

{% block content %}

{% if  pedidos %}
	<h1 class="display-6 text-center mt-4">Lista de pedidos</h1>

	<div class="d-flex flex-column flex-md-row p-4 gap-4 py-md-5 align-items-center justify-content-center">
		<div class="list-group">
		  	{% for pedido in pedidos %}
			    <a href="{{  pedido.get_absolute_url }}" class="list-group-item list-group-item-action d-flex gap-3 py-3" aria-current="true">
			      <div class="d-flex gap-2 w-100 justify-content-between">
			        <div>
			          <h6 class="mb-0">Pedido realizado</h6>
			          	<small class="d-block text-body-secondary">
			          	<svg class="bi me-1" width="1em" height="1em"><use xlink:href="#calendar-event"/></svg>
			          		{{pedido.creado|date:"l, d F"}}
			          	</small>
			        </div>
			        <small class="opacity-50 text-nowrap">{{pedido.creado| naturaltime}}</small>
			      </div>
			    </a>
		    {% endfor %}
		</div>
	</div>

	{% if pedidos.object_list %}
		<div class="d-flex align-items-center justify-content-center">
	        <nav aria-label="Another pagination example">
	          <ul class="pagination pagination-lg flex-wrap">
	          	{% if pedidos.has_previous %}
		            <li class="page-item">
		              <a class="page-link" href="?page={{ pedidos.previous_page_number }}">Previous</a>
		            </li>
		            <li class="page-item">
	          			<a class="page-link" href="?page=1"> 1 </a>
	          		</li>
	            {% endif %}
	            
	            {% if pedidos.has_other_pages %}
	            	<li class="page-item active" aria-current="page">
	              		<a class="page-link" href="?page={{ pedidos.number }}">{{ pedidos.number }}</a>
	            	</li>
	            {% endif %}
	            
	            
	            
	            
	            {% if pedidos.has_next %}
		            <li class="page-item">
			            <a class="page-link" href="?page={{ pedidos.paginator.num_pages }}"> {{ pedidos.paginator.num_pages }}</a>
			        </li>
		            <li class="page-item">
		              <a class="page-link" href="?page={{ pedidos.next_page_number }}">Next</a>
		            </li>
		            
	            {% endif %}
	          </ul>
	        </nav>
    	</div>
    	{% comment %}
    		
    	
		{% if pedidos.has_previous %}
	        <a href="?page=1">&laquo; first</a>
	        <a href="?page={{ pedidos.previous_page_number }}">previous</a>
	    {% endif %}

	    <span class="current">
	        Page {{ pedidos.number }} of {{ pedidos.paginator.num_pages }}.
	    </span>

	    {% if pedidos.has_next %}
	        <a href="?page={{ pedidos.next_page_number }}">next</a>
	        <a href="?page={{ pedidos.paginator.num_pages }}">last &raquo;</a>
		{% endif %}
		{% endcomment %}
		
	{% endif %}

	
	{% else %}
	<h1 class="display-6 text-center mt-4">Sin pedidos...</h1>
	<div class="d-flex flex-column flex-md-row p-4 gap-4 py-md-5 align-items-center justify-content-center">
	  	<div class="list-group">
		    <a href="{% url 'home:index' %}" class="list-group-item list-group-item-action d-flex gap-3 py-3" aria-current="true">
		      <img src="{% static 'img/images.jpeg' %}" alt="twbs" width="32" height="32" class="rounded-circle flex-shrink-0">
		      <div class="d-flex gap-2 w-100 justify-content-between">
		        <div>
		          <h6 class="mb-0">Usted no ha realizado algún pedido aún</h6>
		          <p class="mb-0 opacity-75">para realizarlo vaya al: Catalago de productos.</p>
		        </div>
		      </div>
		    </a>
	  	</div>
	</div>
	
{% endif %}




{% endblock content %}