apps/home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
	path("", views.index, name = 'index'),

	path("add/<int:producto_id>/carrito/", views.add_carrito, name = 'add-carrito'),
	path("delete/<int:producto_id>/carrito/", views.delete_producto_carrito, name = 'delete-carrito'),
	path("vaciar/carrito/", views.limpiar_carrito, name = 'vaciar-carrito'),

	path('crear/pedido/', views.hacer_pedido, name = 'hacer-pedido'),

	path(
		'usuario/<int:usuario_id>/lista/pedidos/', 
		views.lista_pedidos_usuario, 
		name = 'pedido-lista'
	),
	path(
		'usuario/<int:usuario_id>/detalle/<int:pedido_id>/pedido/', 
		views.detalle_pedido_usuario, 
		name = 'pedido'
	),

]

apps/usuario/urls.py
from django.urls import path

from . import views

app_name = 'usuarios'
urlpatterns = [
	path('crear/', views.crear_usuario , name = 'crear-usuario'),
	path('login/', views.login_usuario , name = 'login'),
	path('logout/', views.logout_usuario , name = 'logout'),
	path('confirmar-logout/', views.confirmar_logout , name = 'confirmar-logout'),
	path('config/<int:pk>/usuario/', views.settings_usuario , name = 'config-usuario'),
	path('update/password/<int:pk>/usuario/', views.update_usuario_password , name = 'update-password'),
	path('update/email/<int:pk>/usuario/', views.update_usuario_email , name = 'update-email'),

]

carrito/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.home.urls')),
    path('usuario/', include('apps.usuario.urls'))

]

templates/includes/header.html
{% load static %}

{% block style %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/header.css' %}">
{% endblock style %}

{% include "includes/icons.html" %}

<header>
    <div class="px-3 py-2 navbar-dark bg-dark border-bottom">
      <div class="d-flex flex-column flex-md-row align-items-center pb-3 mb-4 border-bottom">
        <a href="{% url 'home:index' %}" class=" d-flex align-items-center nav-link text-decoration-none {% if request.resolver_match.url_name == 'index'%}text-secondary {% else %}text-white{% endif %}">

          {% if  not request.user.is_authenticated %}
            <svg class="bi d-block mx-auto mb-1" width="24" height="24"><use xlink:href="#home"></use></svg>

            {% else %}
            <svg class="bi d-block mx-auto mb-1" width="24" height="24"><use xlink:href="#cart"/></svg>
          {% endif %}
        
          <span class="mx-2">Inicio</span>
        
        </a>
      

      {% include "./nav.html" %}

      </div>
    </div>
  </header>

templates/includes/messages.html
{% if messages %}
	<div class="p-3">
		{% for message in  messages %}
			<div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
				{{ message }}
				<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
			</div>
		{% endfor %}
	</div>
{% endif %}

templates/includes/nav.html
<nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
	<ul class="nav col-12 col-lg-auto my-2 justify-content-center my-md-0 text-small">
		{% if not request.user.is_authenticated %}
			{% if request.resolver_match.url_name != 'login' %}
				<li>
            <a href="{% url 'usuarios:login' %}" class="nav-link text-white">
              <svg class="bi d-block mx-auto mb-1" width="24" height="24"><use xlink:href="#people-circle"></use></svg>
              Entrar
            </a>
	      </li>
      {% endif %}
      {% if request.resolver_match.url_name != 'crear-usuario' %}
      	<li>
          <a href="{% url 'usuarios:crear-usuario' %}" class="nav-link text-white">
            <svg class="bi d-block mx-auto mb-1" width="24" height="24"><use xlink:href="#people"/></svg>
            Crear Usuario
          </a>
        </li>
      {% endif %}

		{% endif %}

		{% if request.user.is_authenticated %}
			<li>
        <a href="{% url 'usuarios:config-usuario' pk=request.user.pk %}" class="nav-link {% if request.resolver_match.url_name == 'config-usuario'%}text-secondary {% else %}text-white{% endif %} ">
          <svg class="bi d-block mx-auto mb-1" width="24" height="24"><use xlink:href="#gear-wide-connected"/></svg>
          Configuraciones
        </a>
      </li>

      <li>
        <a href="{% url 'usuarios:logout' %}" class="nav-link text-white">
        	<svg class="bi d-block mx-auto mb-1" width="24" height="24"><use xlink:href="#door-closed"/></svg>
          Salir
        </a>
    </li>

    <li>
        <a href="{% url 'home:pedido-lista' usuario_id=request.user.id %}" class="nav-link {% if request.resolver_match.url_name == 'pedido-lista'%}text-secondary {% else %}text-white{% endif %}">
          <svg class="bi d-block mx-auto mb-1" width="24" height="24"><use xlink:href="#file-earmark"/></svg>
          Pedidos
        </a>
      </li>

		{% endif %}
    </ul>
</nav>

templates/includes/total_productos_en_carrito.html
<script type="text/javascript">

		window.addEventListener('load', () => {			
			const ul = document.getElementById("list-productos");

			if(ul){
				const tag = document.getElementById('total-productos');
				tag.innerHTML = `${ul.children.length}`;
			}

		});


</script>